#!/usr/bin/env python
# -*- coding:utf-8 -*-

import turtle
turtle.screensize(90000,90000,"blue")
turtle.pensize(10)
turtle.pencolor('red')
turtle.fillcolor("red")
turtle.speed(1)

# 小写的C
turtle.penup()
turtle.goto(-95,0)
turtle.pendown()
turtle.left(180)
turtle.forward(100)
turtle.right(90)
turtle.forward(150)
turtle.right(90)
turtle.forward(100)

# 大写的S
turtle.penup()
turtle.goto(-75,0)
turtle.pendown()
turtle.forward(100)
turtle.left(90)
turtle.forward(150)
turtle.left(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(150)
turtle.right(90)
turtle.forward(100)

# 大写的C
turtle.penup()
turtle.goto(150,300)
turtle.pendown()
turtle.left(180)
turtle.forward(100)
turtle.left(90)
turtle.forward(300)
turtle.left(90)
turtle.forward(100)

# 大写的E
turtle.penup()
turtle.goto(270,300)
turtle.pendown()
turtle.left(180)
turtle.forward(100)
turtle.left(90)
turtle.forward(300)
turtle.left(90)
turtle.forward(100)
turtle.penup()
turtle.goto(270,150)
turtle.pendown()
turtle.back(100)

# 小写的C
turtle.penup()
turtle.goto(400,0)
turtle.pendown()
turtle.left(180)
turtle.forward(100)
turtle.right(90)
turtle.forward(150)
turtle.right(90)
turtle.forward(100)
turtle.mainloop()
